language: python

python:
  - 3.9
  - 3.8
  - 3.7

install:
  - python --version
  - pip install black
  - pip install codecov

script:
  - black -l 79 --check .
  - python -m unittest

after_success:
  - codecov
